#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  deploy-openrsc-vps.sh — Automated Open-RSC game server setup
#
#  Run on a fresh Ubuntu 22.04+ VPS as root:
#    curl -fsSL https://raw.githubusercontent.com/fuzzynutsxrp-ship-it/fuzzynuts.xyz/main/tools/deploy-openrsc-vps.sh | bash
#
#  Or download and run:
#    bash deploy-openrsc-vps.sh
#
#  What this script does:
#    1. Installs Java 17, MariaDB, Git
#    2. Clones Open-RSC to /opt/openrsc
#    3. Configures database + game server
#    4. Builds the server with Gradle
#    5. Creates a systemd service (auto-restart on crash)
#    6. Opens firewall port 43594
#
#  All steps are idempotent — safe to re-run.
#  Logs: /var/log/openrsc-deploy.log
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

LOGFILE="/var/log/openrsc-deploy.log"
exec > >(tee -a "$LOGFILE") 2>&1

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  FuzzyNuts Open-RSC Server — Automated Deployment"
echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "═══════════════════════════════════════════════════════════"
echo ""

# ── Config ─────────────────────────────────────────────────────

OPENRSC_DIR="/opt/openrsc"
DB_NAME="fuzzynuts_rsc"
DB_USER="openrsc"
DB_PASS="$(openssl rand -hex 16)"
GAME_PORT="43594"
LOG_DIR="/var/log"

# ── Step 1: System packages ───────────────────────────────────

echo "[1/7] Installing system packages..."

apt-get update -qq
apt-get install -y -qq \
  openjdk-17-jdk-headless \
  mariadb-server \
  git \
  curl \
  ufw \
  > /dev/null 2>&1

echo "  Java: $(java -version 2>&1 | head -1)"
echo "  MariaDB: installed"
echo ""

# ── Step 2: MariaDB setup ─────────────────────────────────────

echo "[2/7] Configuring MariaDB..."

systemctl enable mariadb
systemctl start mariadb

# Create database and user (idempotent)
mysql -u root <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOSQL

echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo ""

# ── Step 3: Clone Open-RSC ────────────────────────────────────

echo "[3/7] Cloning Open-RSC..."

if [ -d "${OPENRSC_DIR}/.git" ]; then
  echo "  Already cloned — pulling latest..."
  cd "${OPENRSC_DIR}"
  git pull --quiet
else
  git clone --quiet https://gitlab.com/openrsc/openrsc.git "${OPENRSC_DIR}"
  cd "${OPENRSC_DIR}"
fi

echo "  Repo: ${OPENRSC_DIR}"
echo ""

# ── Step 4: Configure game server ─────────────────────────────

echo "[4/7] Writing server configuration..."

# Write .env with database credentials
cat > "${OPENRSC_DIR}/.env" <<EOF
MARIADB_ROOT_USER=root
MARIADB_ROOT_PASSWORD=
MARIADB_USER=${DB_USER}
MARIADB_PASS=${DB_PASS}
MYSQL_DUMPS_DIR=${OPENRSC_DIR}/Backups
EOF

# Write local.conf with FuzzyNuts branding
cat > "${OPENRSC_DIR}/server/local.conf" <<'EOF'
# FuzzyNuts RSC — local.conf (auto-generated by deploy script)

database:
	db_name: fuzzynuts_rsc

world:
	server_name: FuzzyNuts
	server_name_welcome: FuzzyNuts RSC
	welcome_text: Connect your XRP wallet for rewards!
	display_logo_sprite: true
	server_port: 43594
	ws_server_port: 43494
	want_feature_websockets: true
	max_connections_per_ip: 20
	max_connections_per_second: 20
	max_packets_per_second: 100
	max_logins_per_second: 2
	max_password_guesses_per_five_minutes: 10
	network_flood_ip_ban_minutes: 5
	max_players: 200
	max_players_per_ip: 5
	member_world: true
	world_number: 1
	player_level_limit: 99
	game_tick: 640
	walking_tick: 640
	want_custom_walking_speed: false
	combat_exp_rate: 1
	skilling_exp_rate: 1
	wilderness_boost: 0
	skull_boost: 0
	double_exp: false
	want_fatigue: true
	features_sleep: true
	npc_respawn_multiplier: 1.0
	want_registration_limit: true
	registration_limit_count: 3
	idle_timer: 300000
	connection_timeout: 15
	packet_limit: 100
	connection_limit: 10
	auto_save: 30000
	show_tutorial_skip_option: true
	skip_tutorial_gives_items: false
	client_version: 10009
	enforce_custom_client_version: false
	server_location: USA
	location_data: 0
	based_map_data: 64
	based_config_data: 85
	respawn_location_x: 120
	respawn_location_y: 648
	want_pcap_logging: true
EOF

echo "  Config: ${OPENRSC_DIR}/server/local.conf"
echo "  Env: ${OPENRSC_DIR}/.env"
echo ""

# ── Step 5: Build with Gradle ─────────────────────────────────

echo "[5/7] Building server with Gradle (this may take a few minutes)..."

cd "${OPENRSC_DIR}"

if [ -f "gradlew" ]; then
  chmod +x gradlew
  ./gradlew :server:build --no-daemon --quiet 2>&1 | tail -5
elif command -v gradle &> /dev/null; then
  gradle :server:build --no-daemon --quiet 2>&1 | tail -5
else
  echo "  Installing Gradle wrapper..."
  # Open-RSC includes gradlew; if missing, bootstrap it
  if [ ! -f "gradlew" ]; then
    echo "  ERROR: gradlew not found. Check the Open-RSC repo."
    exit 1
  fi
fi

echo "  Build complete."
echo ""

# ── Step 6: Systemd service ───────────────────────────────────

echo "[6/7] Creating systemd service..."

# Find the server JAR
SERVER_JAR=$(find "${OPENRSC_DIR}/server/build/libs" -name "*.jar" -not -name "*-sources.jar" | head -1)

if [ -z "$SERVER_JAR" ]; then
  echo "  WARNING: Server JAR not found in build/libs. Service will need manual JAR path."
  SERVER_JAR="${OPENRSC_DIR}/server/build/libs/server-1.0-SNAPSHOT.jar"
fi

cat > /etc/systemd/system/openrsc.service <<EOF
[Unit]
Description=FuzzyNuts Open-RSC Game Server
After=network.target mariadb.service

[Service]
Type=simple
User=root
WorkingDirectory=${OPENRSC_DIR}
ExecStart=/usr/bin/java -server -Xmx512m -cp "${SERVER_JAR}:${OPENRSC_DIR}/server/build/libs/*" com.openrsc.server.Server -Dconf=local
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo "  Service: /etc/systemd/system/openrsc.service"
echo ""

# ── Step 7: Firewall ──────────────────────────────────────────

echo "[7/7] Configuring firewall..."

ufw --force enable > /dev/null 2>&1
ufw allow 22/tcp comment "SSH" > /dev/null 2>&1
ufw allow ${GAME_PORT}/tcp comment "Open-RSC game server" > /dev/null 2>&1
ufw allow 3306/tcp comment "MariaDB (optional, remove if not needed)" > /dev/null 2>&1

echo "  Port ${GAME_PORT}/tcp: open"
echo ""

# ── Done ───────────────────────────────────────────────────────

echo "═══════════════════════════════════════════════════════════"
echo "  DEPLOYMENT COMPLETE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Database credentials (save these!):"
echo "    DB Name: ${DB_NAME}"
echo "    DB User: ${DB_USER}"
echo "    DB Pass: ${DB_PASS}"
echo ""
echo "  Next steps:"
echo "    1. Start the server:"
echo "       systemctl enable --now openrsc"
echo ""
echo "    2. Check it's running:"
echo "       systemctl status openrsc"
echo ""
echo "    3. View logs:"
echo "       journalctl -u openrsc -f"
echo ""
echo "    4. Set DNS A record:"
echo "       game.fuzzynuts.xyz → $(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_VPS_IP')"
echo "       Cloudflare: set to DNS-only (grey cloud)"
echo ""
echo "    5. In Railway dashboard, set:"
echo "       GAME_SERVER_READY=true"
echo "       OPENRSC_GAME_ENDPOINT=fuzzynuts.xyz:43594"
echo ""
echo "  Log file: ${LOGFILE}"
echo ""
