#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  deploy-openrsc-vps.sh — Automated Open-RSC game server setup
#
#  Run on a fresh Ubuntu 22.04+ VPS as root:
#    curl -fsSL https://raw.githubusercontent.com/fuzzynutsxrp-ship-it/fuzzynuts.xyz/main/tools/deploy-openrsc-vps.sh | bash
#
#  What this script does:
#    1. Installs Java 17, Ant, MariaDB, Git, Make
#    2. Clones Open-RSC to /opt/openrsc
#    3. Configures database + game server
#    4. Builds the server with Ant (via make)
#    5. Creates a systemd service (auto-restart on crash)
#    6. Opens firewall port 43594
#
#  All steps are idempotent — safe to re-run.
#  Logs: /var/log/openrsc-deploy.log
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

LOGFILE="/var/log/openrsc-deploy.log"
exec > >(tee -a "$LOGFILE") 2>&1

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  FuzzyNuts Open-RSC Server — Automated Deployment"
echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "═══════════════════════════════════════════════════════════"
echo ""

# ── Config ─────────────────────────────────────────────────────

OPENRSC_DIR="/opt/openrsc"
DB_NAME="fuzzynuts_rsc"
DB_USER="openrsc"
DB_PASS="$(openssl rand -hex 16)"
GAME_PORT="43594"

# ── Step 1: System packages ───────────────────────────────────

echo "[1/7] Installing system packages..."

apt-get update -qq
apt-get install -y -qq \
  openjdk-17-jdk-headless \
  ant \
  make \
  mariadb-server \
  git \
  curl \
  ufw \
  > /dev/null 2>&1

echo "  Java: $(java -version 2>&1 | head -1)"
echo "  Ant: $(ant -version 2>&1 | head -1)"
echo "  MariaDB: installed"
echo ""

# ── Step 2: MariaDB setup ─────────────────────────────────────

echo "[2/7] Configuring MariaDB..."

systemctl enable mariadb
systemctl start mariadb

mysql -u root <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOSQL

echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo ""

# ── Step 3: Clone Open-RSC ────────────────────────────────────

echo "[3/7] Cloning Open-RSC..."

if [ -d "${OPENRSC_DIR}/.git" ]; then
  echo "  Already cloned — pulling latest..."
  cd "${OPENRSC_DIR}"
  git pull --quiet
else
  git clone --quiet https://gitlab.com/openrsc/openrsc.git "${OPENRSC_DIR}"
  cd "${OPENRSC_DIR}"
fi

echo "  Repo: ${OPENRSC_DIR}"
echo ""

# ── Step 4: Configure game server ─────────────────────────────

echo "[4/7] Writing server configuration..."

cat > "${OPENRSC_DIR}/.env" <<EOF
MARIADB_ROOT_USER=root
MARIADB_ROOT_PASSWORD=
MARIADB_USER=${DB_USER}
MARIADB_PASS=${DB_PASS}
MYSQL_DUMPS_DIR=${OPENRSC_DIR}/Backups
EOF

cat > "${OPENRSC_DIR}/server/local.conf" <<'EOF'
# FuzzyNuts RSC — local.conf (auto-generated by deploy script)

database:
	db_name: fuzzynuts_rsc

world:
	server_name: FuzzyNuts
	server_name_welcome: FuzzyNuts RSC
	welcome_text: Connect your XRP wallet for rewards!
	display_logo_sprite: true
	server_port: 43594
	ws_server_port: 43494
	want_feature_websockets: true
	max_connections_per_ip: 20
	max_connections_per_second: 20
	max_packets_per_second: 100
	max_logins_per_second: 2
	max_password_guesses_per_five_minutes: 10
	network_flood_ip_ban_minutes: 5
	max_players: 200
	max_players_per_ip: 5
	member_world: true
	world_number: 1
	player_level_limit: 99
	game_tick: 640
	walking_tick: 640
	want_custom_walking_speed: false
	combat_exp_rate: 1
	skilling_exp_rate: 1
	wilderness_boost: 0
	skull_boost: 0
	double_exp: false
	want_fatigue: true
	features_sleep: true
	npc_respawn_multiplier: 1.0
	want_registration_limit: true
	registration_limit_count: 3
	idle_timer: 300000
	connection_timeout: 15
	packet_limit: 100
	connection_limit: 10
	auto_save: 30000
	show_tutorial_skip_option: true
	skip_tutorial_gives_items: false
	client_version: 10009
	enforce_custom_client_version: false
	server_location: USA
	location_data: 0
	based_map_data: 64
	based_config_data: 85
	respawn_location_x: 120
	respawn_location_y: 648
	want_pcap_logging: true
EOF

echo "  Config: ${OPENRSC_DIR}/server/local.conf"
echo ""

# ── Step 5: Initialize database ───────────────────────────────

echo "[5/8] Initializing game database..."

DB_DIR="${OPENRSC_DIR}/server/inc/sqlite"
mkdir -p "${DB_DIR}"

if [ ! -f "${DB_DIR}/${DB_NAME}.db" ]; then
  # Copy from the default Open-RSC database as a template
  if [ -f "${DB_DIR}/openrsc.db" ]; then
    cp "${DB_DIR}/openrsc.db" "${DB_DIR}/${DB_NAME}.db"
    echo "  Database: ${DB_DIR}/${DB_NAME}.db (from openrsc template)"
  else
    touch "${DB_DIR}/${DB_NAME}.db"
    echo "  Database: ${DB_DIR}/${DB_NAME}.db (empty — server will init)"
  fi
else
  echo "  Database: ${DB_DIR}/${DB_NAME}.db (already exists)"
fi
echo ""

# ── Step 6: Build with Ant ────────────────────────────────────

echo "[6/8] Building server with Ant (this may take a few minutes)..."

cd "${OPENRSC_DIR}"
make compile 2>&1 | tail -10

echo "  Build complete."
echo ""

# ── Step 7: Systemd service ───────────────────────────────────

echo "[7/8] Creating systemd service..."

cat > /etc/systemd/system/openrsc.service <<EOF
[Unit]
Description=FuzzyNuts Open-RSC Game Server
After=network.target mariadb.service

[Service]
Type=simple
User=root
WorkingDirectory=${OPENRSC_DIR}/server
ExecStart=/usr/bin/ant runserverzgc -DconfFile=local
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo "  Service: /etc/systemd/system/openrsc.service"
echo ""

# ── Step 8: Firewall ──────────────────────────────────────────

echo "[8/8] Configuring firewall..."

ufw --force enable > /dev/null 2>&1
ufw allow 22/tcp comment "SSH" > /dev/null 2>&1
ufw allow ${GAME_PORT}/tcp comment "Open-RSC game server" > /dev/null 2>&1

echo "  Port ${GAME_PORT}/tcp: open"
echo ""

# ── Start server ───────────────────────────────────────────────

echo "Starting game server..."
systemctl enable --now openrsc
sleep 5

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  DEPLOYMENT COMPLETE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Database credentials (save these!):"
echo "    DB Name: ${DB_NAME}"
echo "    DB User: ${DB_USER}"
echo "    DB Pass: ${DB_PASS}"
echo ""
echo "  Game server status:"
systemctl status openrsc --no-pager 2>&1 | head -5 || true
echo ""
echo "  Port check:"
ss -tlnp | grep ${GAME_PORT} || echo "  WARNING: Port ${GAME_PORT} not listening yet"
echo ""
echo "  Log file: ${LOGFILE}"
echo ""
